var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-23322918-1']);
_gaq.push(['_setDomainName', '.focus.cn']);
_gaq.push(['_setAllowLinker', true]);
_gaq.push(['_setAllowHash', false]);
_gaq.push(['_addOrganic', 'zhidao.baidu', 'word']);
_gaq.push(['_addOrganic', 'news.baidu', 'word']);
_gaq.push(['_addOrganic', 'post.baidu', 'kw']);
_gaq.push(['_addOrganic', 'tieba.baidu', 'kw']);
_gaq.push(['_addOrganic', 'mp3.baidu', 'word']);
_gaq.push(['_addOrganic', 'image.baidu', 'word']);
_gaq.push(['_addOrganic', 'top.baidu', 'word']);
_gaq.push(['_addOrganic', 'news.google', 'q']);
_gaq.push(['_addOrganic', 'baidu', 'word']);
_gaq.push(['_addOrganic', 'baidu', 'kw']);
_gaq.push(['_addOrganic', 'image.soso', 'w']);
_gaq.push(['_addOrganic', 'music.soso', 'w']);
_gaq.push(['_addOrganic', 'post.soso', 'kw']);
_gaq.push(['_addOrganic', 'wenwen.soso', 'sp']);
_gaq.push(['_addOrganic', 'soso', 'w']);
_gaq.push(['_addOrganic', 'bing', 'q']);
_gaq.push(['_addOrganic', '3721', 'name']);
_gaq.push(['_addOrganic', 'youdao', 'q']);
_gaq.push(['_addOrganic', 'vnet', 'kw']);
_gaq.push(['_addOrganic', 'news.sogou', 'query']);
_gaq.push(['_addOrganic', 'mp3.sogou', 'query']);
_gaq.push(['_addOrganic', 'pic.sogou', 'query']);
_gaq.push(['_addOrganic', 'blogsearch.sogou', 'query']);
_gaq.push(['_addOrganic', 'sogou', 'query']);
_gaq.push(['_addOrganic', 'so.360.cn', 'q']);
_gaq.push(['_addOrganic', '360sou.com', 'q']);
_gaq.push(['_addIgnoredRef','house.focus.cn']);
_gaq.push(['_addIgnoredRef','home.sohu.com']);
_gaq.push(['_addIgnoredRef','garden.sohu.com']);
_gaq.push(['_setCampaignCookieTimeout', 86400000]);
_gaq.push(['_trackPageview',location.pathname+location.search+'#news']);
_gaq.push(['_trackPageloadtime']);
_gaq.push(['_setSessionCookieTimeout', 900000]);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();